version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-vscode-dev.dockerfile
    command: sleep infinity
    depends_on:
      - database
    volumes:
      - ./:/workspace

  database:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
